### ISSUE TITLE
Amélioration : Notification sur l'icône

### ISSUE THREAD

**Issue by Aymkdn** [garoloup/SendToFreebox#1]
Merci pour cet addon :-)

Il serait cool d'avoir une notification sur l'icône de l'addon pour signaler que le fichier envoyé a bien été pris en compte et qu'il commence à être téléchargé, car l'autre jour j'ai envoyé un premier fichier (qui a bien commencé à se télécharger), puis un deuxième qui n'a jamais été pris en compte. Avec une petite notification au niveau de l'icône on pourrait savoir de suite si l'addon a bien pris en compte notre demande.

Ensuite dès qu'on a envoyé un fichier à l'addon, il pourrait faire un refresh régulièrement pour voir l'état des téléchargements et affiché une petite icône du genre ✓ pour indiquer que tout est terminé.

Je vais regarder ton code aussi dès que j'ai un moment pour voir si je peux proposer des choses :-)

**Comment by garoloup** [comment]
Salut,
Content que ca puisse servir...
Bizarre...
J'ai commencé a utiliser les badges pour les erreurs...
Je voulais aussi les utiliser pour les ajouts effectivement.
Pas encore eu le temps: j'ai préféré releaser car on ne finit jamais d'améliorer

Le pulling me gene cependant mais tant que je n'ai mis en place de websocket il n' a pas trop le choix.

Si tu as le courage et que tu es plus expérimenté que moi je suis preneur de tes conseils et contributions

**Comment by garoloup** [comment]
J'ai ajouté un badge "+1" sur ajout d'URL réussi sinon badge "Err" (on a que 4 caractères dispo)

**Comment by Aymkdn** [comment]
Alors, j'ai mis à jour l'extension en v1.1, mais ça ne marche plus du tout maintenant… J'ai essayé d'envoyer plusieurs liens, mais rien ne se passe.

Tout semble pourtant correct au niveau de l'addon / des droits.

Au fait, comment on peut installer la version disponible sur Github plutôt que celle du store ? J'ai essayé de télécharger en .zip puis te renommer en .xpi mais ça ne marche pas ^^

Merci

**Comment by garoloup** [comment]
Je viens de publier la v1.1 sur firefox et chrome en ajoutant le badge.

Pour ajouter une extension sans passer par le store:
- tu dezippes 
- dans firefox tu saisies "about:debugging" dans la barre d'adresse 
- ou bien dans chrome tu saisies "chrome://extensions/"
- Tu charge soit le manifest pour FF ou bien selectionne le repertoire pour chrome

**Comment by Aymkdn** [comment]
Merci.

Je confirme que la version Github fonctionne mais pas celle du store de Firefox.

Je confirme aussi que si on a une session d'ouverte sur mafreebox.freebox.fr avec le navigateur, alors l'addon n'arrive pas à envoyer de demande d'association à la Freebox.

**Comment by garoloup** [comment]
Salut 

J’ai encore détesté et l’extension depuis les store firefox et chrome fonctionne
