### ISSUE TITLE
Nouvelle version…

### ISSUE THREAD

**Issue by Aymkdn** [garoloup/SendToFreebox#2]
Bonjour,

Merci encore d'avoir partagé le code de ton extension ! J'ai commencé à corriger quelques petites choses, puis finalement je me suis dit que ça serait plus simple que je réécrive entièrement l'extension car il y avait beaucoup de code en double, de choses inutiles, et c'était difficile à modifier…

Les nouveautés : 
- Tout est en français
- Mini guide sur comment activer l'application et lui donner les droits (directement dans l'addon)
- Badge qui s'anime quand on ajoute des téléchargements
- Badge qui affiche le nombre de téléchargements en cours et quand ils sont terminés
- Les téléchargements en cours sont affichés quand on clique sur l'icône
- Boutons pour pause/reprendre/stopper les téléchargement depuis l'icône

Tout n'est pas parfait évidemment… et je suis ouvert aux suggestions !

J'ai trouvé pourquoi ton addon déconne lorsqu'on est logué sur FreeboxOS : un cookie de session est envoyé vers FreeboxOS et cela crée un comportement différent de la part de l'API quand ce cookie est présent ! Il suffit de rajouter un `{credential:'omit'}` pour éviter cela.

Tu peux voir mon code là : https://github.com/Aymkdn/SendToFreebox

Comme je l'ai indiqué, j'ai entièrement réécrit l'extension, mais j'ai utilisé la tienne comme base/"template". Du coup, je te propose : soit ma version te plait et je te fais un _pull request_ (puisque c'est un _fork_ de la tienne) puis tu la publies sur les stores en ton nom, soit ça ne te plait pas et dans ce cas je trouverai un nouveau nom et une nouvelle icône et je la publierai sur les stores en mon nom !

J'espère que tu auras compris que mon but n'est pas de "faire de l'ombre" à ton addon, mais de l'améliorer, et c'est pourquoi j'ai bossé dessus cette semaine. 👍 

Merci 🙏

PS : je suis sous Firefox, donc pas testé dans Chrome mais j'ai cru comprendre qu'avec WebExtension les addons marchaient sur les deux ?!

**Comment by garoloup** [comment]
Salut 
Merci pour ta contribution.
J'ai parcouru ton code rapidement duquel j'apprends beaucoup de choses sur javascript dans lequel je débute. Ta version est bien meilleure et assez différente.
Je pourrai la tester ce w-e. Si son comportement est similaire avec un meilleur code et que tu peux aussi m'aider dans le support futur eventuel, on peut merger (faut que je regarde comment accepter un pull request: aussi debutant sur github)

Je testerai aussi sous chrome car même si les extensions existent, il semble y avoir des différences et l'enregistrement du compte n'est pas gratuit meme si trés abordable.

**Comment by Aymkdn** [comment]
> tu peux aussi m'aider dans le support futur eventuel

Pas de soucis pour ça ! Tu pourras me mettre comme contributeur sur ce projet comme ça je pourrai participer activement si besoin :)

**Comment by garoloup** [comment]
Bonne nouvelle car elle fonctionne aussi sous chrome.
L'association est simple, et l'usage plus conviviale et plus robuste notamment avec l'option omit (pas encore testé)
Dommage de ne plus avoir la section setting : pourrait etre utile pour des freebox distantes.
Plus qu'a comprendre comment gerer une pull request et t'ajouter en contributeur

**Comment by Aymkdn** [comment]
> Dommage de ne plus avoir la section setting : pourrait etre utile pour des freebox distantes.

J'ai en effet retiré cette partie car je ne suis pas sûr qu'il y ait un besoin ?! Si des gens demandent cette fonctionnalité alors ça peut être ajouté plus tard !

Merci 😊
