### ISSUE TITLE
Modification du README

### ISSUE THREAD

**Issue by Aymkdn** [garoloup/SendToFreebox#4]
Si tu me donnes des accès au repository, alors je modifierai le README pour être aligné avec la nouvelle version – sinon je le modifie dans mon fork et je te fais un pull request. Comme tu préfères.

C'est ce README qui est automatiquement utilisé par les store ? Ou alors tu fais un copier/coller ? Car il serait bon d'inviter les gens sur Github plutôt que sur le forum Univers Freebox, que ce soit pour les demandes d'aide ou d'amélioration.

Concernant la publication sur les stores, je te laisse gérer évidemment !

**Comment by garoloup** [comment]
Salut 
Je viens de t'ajouter a la liste des contributeurs.
Le readme n'est pas automatiquement repris mais je l'utilise.
Avant de publier il daudra que je fasse des screenshots 
J'ai modifié l'affichage du filename pour avoir un nom court.
Sous chrome la fenetre est etroite: j'avais deja eu ce souci mais pas résolu en definissant la largeur de la colonne mais en fixant la largeur de la popup
Si tu as une suggestion ...

**Comment by Aymkdn** [comment]
> Je viens de t'ajouter a la liste des contributeurs.

Super ! Merci :-)

> Le readme n'est pas automatiquement repris mais je l'utilise.

OK. Je modifierai le README demain matin.

> Sous chrome la fenetre est etroite: j'avais deja eu ce souci mais pas résolu en definissant la largeur de la colonne mais en fixant la largeur de la popup
> Si tu as une suggestion ...

En regardant vite fait Stackoverflow, il faudrait utiliser un `min-width` et `min-height` sur `html`, avec un maximum de 800×600 (au-delà c'est ignoré). Je testerai sous Chrome demain matin et je verrai ce que ça donne et comment corriger !

**Comment by garoloup** [comment]
J'ai fait la modif de largeur: c'est mieux.
J'ai empèché le word wrap du nom de fichier court

**Comment by garoloup** [comment]
C'est publié sur Firefox.
Merci pour ta contribution majeure: 

Je t'ai mentionné dans la page de l'extension.

**Comment by Aymkdn** [comment]
> J'ai fait la modif de largeur: c'est mieux.

OK, donc pas besoin que je regarde ?

> J'ai empèché le word wrap du nom de fichier court

J'ai vu. Bien joué !

> C'est publié sur Firefox.
> Je t'ai mentionné dans la page de l'extension.

Merci :-)

Je viens de mettre à jour le [README](https://github.com/garoloup/SendToFreebox/blob/master/README.md). J'espère que ça te convient. Je te laisse le corriger sinon.

**Comment by garoloup** [comment]
Salut
Je suis pas expert en HTML5 mais j’ai suivi ton conseil donc ca doit passer.
Merci encore pour ton aide
fred
