### ISSUE TITLE
TypeError: NetworkError

### ISSUE THREAD

**Issue by Djedouas** [garoloup/SendToFreebox#5]
Since last Firefox update, the extension does no longer work...

The icon pops up the following error:
`TypeError: NetworkError when attempting to fetch resource.`

Mozilla Firefox for Ubuntu - 86.0 (64 bits)

**Comment by Aymkdn** [comment]
J'ai Firefox 86 (64 bits sous Windows) et ça fonctionne. C'est peut-être un problème relatif à ta connectivité ?

**Comment by Djedouas** [comment]
Merci pour la réponse rapide...
J'ai redémarré ma freebox et réinstallé l'extension.
Je n'ai plus l'erreur, mais le popup de configuration qui demande de valider l'appli depuis l'écran tactile de la freebox...
mais l'écran tactile ne demande rien.

**Comment by Aymkdn** [comment]
Étrange… 

Tu peux essayer de tout remettre à zéro : 
1. Suppression de l'addon de Firefox
2. Connecte toi sur http://mafreebox.freebox.fr puis dans **Paramètres de la Freebox** va dans **Gestion des Accès** :
    - Vérifie que tu autorises les nouvelles applications    
       ![image](https://user-images.githubusercontent.com/946315/110249328-f26c0a00-7f75-11eb-9f40-bfade43bcbed.png)
    - Puis dans l'onglet **Applications** supprime l'application "SendToFreebox"    
      ![image](https://user-images.githubusercontent.com/946315/110249365-1cbdc780-7f76-11eb-9267-b59058120905.png)
3. Réinstalle l'addon sur Firefox et recommence la configuration

**Comment by Djedouas** [comment]
Merci pour l'info, je cherchais justement où réinitialiser l'accès de l'appli sur la freebox.
Mais hélas, même après avoir révoqué l'accès, redémarré la box, réinstallé l'extension, lorsque je demande à l'extension de configurer la box, l'écran tactile de celle-ci ne bouge pas...
Ca avait marché nickel du premier coup à l'origine...

**Comment by Aymkdn** [comment]
Tu as bien vérifié que tu autorises les nouvelles applications ? Essaie aussi un nouveau reboot de la Freebox Serveur...

**Comment by Djedouas** [comment]
Oui j'autorise bien les nouvelles applis, la case est cochée :slightly_frowning_face: 

Je pense que je vais laisser tomber...

**Comment by Aymkdn** [comment]
Désolé, pas d'autres idées...

**Comment by Djedouas** [comment]
Merci en tout cas, si je trouve une solution je commenterai ici
