### ISSUE TITLE
Possibilité d'ajout à distance

### ISSUE THREAD

**Issue by SebCorbin** [garoloup/SendToFreebox#6]
Dans le cas où je suis pas chez moi, j'aimerais pouvoir ajouter un téléchargement dans mon interface, à distance, en configurant simplement l'ip/nom de domaine de ma freebox

**Comment by SebCorbin** [comment]
Pour tester, j'ai téléchargé l'add-on et modifié en mettant mon nom de domaine, ça fonctionne bien (l'activation se fait en local, puis l'appToekn reste valide à distance)

Proposition d'attaque :

- [ ] Ajouter un champ texte dans la step 1 avec la valeur par défaut http://mafreebox.freebox.fr
- [ ] enregistrer cette valeur dans les settings
- [ ] l'utiliser partout où elle est mentionnée

**Comment by Aymkdn** [comment]
Le truc c'est que le projet appartient à @garoloup, ainsi que l'addon sur les store. Donc faut voir s'il est d'accord pour ces modifications, et si on lui propose une pull request, s'il voudra bien le pusher dans le store !

**Comment by garoloup** [comment]
Salut
Si les changements sont testés ok par vous 2 je peux released

PS:
Je ne suis plus chez free

**Comment by SebCorbin** [comment]
Je ne sais pas si c'est possible et si tu es intéressé de transférer le projet (vu que tu n'es plus chez Free) ?

**Comment by garoloup** [comment]
Je prefererais que tu testes aussi sur FF stp.

Ca semble possible: https://support.google.com/chrome_webstore/contact/one_stop_support?visit_id=638266813400543968-2747584955&rd=1

As tu un compte de Chrome Web Store developer ?
